# 5/15/2014
'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
def fib(value1, value2, sum):
	if (value1 > 4000000):
		print sum
		return 0
	else :
		value3 = value1 + value2
		if (value3 % 2 == 0):
			sum = sum + value3
		fib(value2, value3, sum)

a = 1
b = 1
fib(a, b, 0)